import ReactDOMServer from "react-dom/server";
import AboutSection from "@/components/AboutSection";
import ContactSection from "@/components/ContactSection";
import HeroSection from "@/components/HeroSection";
import Logo from "@/components/Logo";
import WorkSection from "@/components/WorkSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cody Constant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={`data:image/svg+xml,${encodeURIComponent(
            ReactDOMServer.renderToStaticMarkup(
              <Logo strokeStyle={{ stroke: "#38bdf8" }} />
            )
          )}`}
        />
      </Head>
      <main>
        <HeroSection />
        <AboutSection />
        <WorkSection />
        <ContactSection />
      </main>
    </>
  );
}
